from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
import re
from typing import List, Dict, Any

def parse_markdown_to_text_frame(text_frame, markdown_text):
    """
    Parses simple markdown (bullets, bold) into a PPTX text frame.
    """
    if not markdown_text:
        return

    lines = markdown_text.split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        # Determine indent level (bullets)
        level = 0
        clean_line = line
        
        if line.startswith('- ') or line.startswith('* '):
            level = 0
            clean_line = line[2:]
        elif line.startswith('  - ') or line.startswith('  * '):
            level = 1
            clean_line = line[4:]
            
        p = text_frame.add_paragraph()
        p.level = level
        
        # Handle Bold (**text**)
        # Split by bold markers
        parts = re.split(r'(\*\*.*?\*\*)', clean_line)
        
        for part in parts:
            run = p.add_run()
            if part.startswith('**') and part.endswith('**'):
                run.text = part[2:-2]
                run.font.bold = True
            else:
                run.text = part
                
        p.space_after = Pt(10)

def generate_pptx_document(project_title: str, nodes: List[Dict[str, Any]], output_path: str):
    """
    Generates a PPTX file from the project structure.
    """
    prs = Presentation()
    
    # 1. Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = project_title
    subtitle.text = "Generated by Training Consolidation Workbench"
    
    # 2. Content Slides
    # Sort nodes by order
    sorted_nodes = sorted(nodes, key=lambda x: x.get('order', 0))
    
    content_slide_layout = prs.slide_layouts[1] # Title and Content
    
    for node in sorted_nodes:
        slide = prs.slides.add_slide(content_slide_layout)
        
        # Title
        title = slide.shapes.title
        title.text = node.get('title', 'Untitled Section')
        
        # Content
        content_md = node.get('content_markdown', '')
        
        # Placeholders[1] is usually the body text frame
        if len(slide.placeholders) > 1:
            body_shape = slide.placeholders[1]
            if not body_shape.has_text_frame:
                continue
            
            tf = body_shape.text_frame
            tf.clear() # Clear default empty paragraph
            
            if content_md:
                parse_markdown_to_text_frame(tf, content_md)
            else:
                p = tf.add_paragraph()
                p.text = "(No content)"
                p.font.italic = True
                
    prs.save(output_path)
    return output_path
